### ISSUE TITLE
Issue adding times to dict

### ISSUE THREAD

**Issue by mlomnitz** [CDIPS-AI-2017/pensieve#28]
I ran into an error in the following line 
https://github.com/CDIPS-AI-2017/pensieve/blob/master/pensieve/pensieve.py#L389
when running the latest version of pensieve. The error message was as follows:

AttributeError: 'spacy.tokens.span.Span' object has no attribute 'strip'

**Comment by sam-dixon** [comment]
Change to 'time.text.strip()'

**Comment by sam-dixon** [comment]
Was this resolved?
